### ISSUE TITLE
RE: More of a Thank You/Seth

### ISSUE THREAD

**Issue by silver2row** [john-davies/Blog-code-files#1]
Hello Sir,

Way to go! I am transferring items now via your script from an older version of Nat GEO. It spanned from the beginning to '09 instead of '12 like your software.

Seth

P.S. I left some comments on your Wordpress page too. Thank you. I used an updated version of the imagemagick source, i.e. --version 7.0.10-31. It works like a charm!

**Comment by chipzoller** [comment]
I know it's been a while, but I wanted to post a similar message of thanks just as @silver2row did. Because of your article and code here, I decided to buy this DVD set for myself so I could enjoy these historic issues in the years to come.

I also expanded your script to both make it a little more resilient (some images have spaces in their file names which need to be parsed properly) and allow a whole decade of issues to be processed at one time. I'll post what I've done here in case it helps someone else.

<details><summary>Expanded scripts</summary>
<p>

I expanded this script being on WSL on Windows and used the `magick` binary offered [here](https://imagemagick.org/script/download.php) to make installation easier. Comments also show a mount command so the DVD can be mounted in WSL so the script has access. From there, point it at a decade directory on the mounted DVD and a local path where you want the final PDFs to be assembled. `cng2jpg` must also be built beforehand.

```sh
#! /bin/bash
# Mount DVD drive: sudo mount -t drvfs D: /mnt/d
# Example:
# ./mm.sh /mnt/d/disc6/images/191x/ ~/natgeo/Blog-code-files/natgeo_script
echo "Nat Geo Magazine PDF maker"

input_dir=$1
output_dir=$2

mkdir -p $output_dir

find "$input_dir" -mindepth 1 -maxdepth 1 -type d | while read -r sub_dir
do
    echo "Processing subdirectory: $sub_dir"
    sub_output_dir="$output_dir/$(basename "$sub_dir")"
    mkdir -p "$sub_output_dir"

    find "$sub_dir" -maxdepth 1 -type f -name '*.cng' | while read -r filename
    do
        echo "Converting: $filename"
        output_filename="$sub_output_dir/$(basename "$filename" .cng).jpg"
        ./cng2jpg "$filename" "$output_filename"
    done

    subdir_name=$(basename "$sub_dir")
    echo "Creating ${subdir_name}.pdf"
    ./magick "$sub_output_dir"/*.jpg -density 72 "$output_dir/${subdir_name}.pdf"
	echo "Clearing temp JPG files"
	rm -f "$sub_output_dir"/*.jpg
done
```

And then if you wanted to move all of them somewhere else.

```sh
#! /bin/bash
# Moves PDF files from input directory to output directory
# Example:
# ./move.sh /home/chip/natgeo/Blog-code-files/natgeo_script /mnt/c/Users/chipz/Downloads/natgeo
echo "Moving PDF files"
input_dir=$1
output_dir=$2
mkdir -p $output_dir
find "$input_dir" -maxdepth 1 -type f -name '*.pdf' -exec mv {} $output_dir \;
echo "Done"
```


</p>
</details>

Thank you sincerely for your work and article!

**Comment by john-davies** [comment]
> I know it's been a while, but I wanted to post a similar message of thanks just as [@silver2row](https://github.com/silver2row) did. Because of your article and code here, I decided to buy this DVD set for myself so I could enjoy these historic issues in the years to come.
> 
> I also expanded your script to both make it a little more resilient (some images have spaces in their file names which need to be parsed properly) and allow a whole decade of issues to be processed at one time. I'll post what I've done here in case it helps someone else.
> Expanded scripts
> 
> Thank you sincerely for your work and article!

( Sorry been on holiday! ) 

I'm glad it's been of help and thanks for the updates.
